spring.application.name=travel-recommendation

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/travel_project_database}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:${DB_PASSWORD}}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

opentripmap.api.key=${OPENTRIPMAP_KEY}
liteapi.api.key=${LITEAPI_KEY}

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

server.port=${PORT:8080}